turnoff: null
conv_layers:
  - name: conv1
    out_channels: 4
    kernel_size: 3
    stride: 1
    padding: 0
    pooling_kernel_size: 2
    pooling_stride: 2
    pooling_padding: 0
    dropout: 0.1
  - name: conv2
    out_channels: 3
    kernel_size: 3
    stride: 1
    padding: 0
    pooling_kernel_size: 2
    pooling_stride: 2
    pooling_padding: 0
    dropout: 0.1