num_chains: 3
n_fft: 2048
win_length: 2048
hop_length: 512
normalized: True
conv_layers:
  - name: conv1
    out_channels: 4096
    kernel_size: 3
    stride: 1
    padding: 0
    pooling_kernel_size: 3
    pooling_stride: 2
    pooling_padding: 0
    dropout: 0.1
  - name: conv2
    out_channels: 1024
    kernel_size: 1
    stride: 1
    padding: 0
    pooling_kernel_size: 2
    pooling_stride: 2
    pooling_padding: 0
    dropout: 0.1