BATCH_SIZE = 8
LOG_DIR = 'logging'
ENABLE_LOGGING = False
ENABLE_CHECKPOINTING = True
DEVICES = 'auto'
ACCELERATOR = 'auto'
NUM_EPOCHS = 1
MAX_SEQ_SIZE = 1024
NUM_CLASSES = 7  # 6 standard + 1 other
MODEL_TYPE = 'cnn1d'
RESUME_CKPT = False
W_OUT = 5
NUM_WORKERS = 0
DATASET_FILE_IDX = 'all'
LEARNING_RATE = 1e-3
RD_SEED = 0
N_SPLITS = 2
POS_IDX = int(W_OUT / 2)

# print(POS_IDX)

